### ISSUE TITLE
Add folders for each player

### ISSUE THREAD

**Issue by UnEnanoMas** [TATCHAN0825/joinskinsave#1]
Idea:

I have been testing the plugin and I have seen that the player's data is overwritten if it enters with another skin, I had thought about whether in data plugins you could create folders for each player, and in those folders put all the skins with which the player enters

For example "UnEnanoMas.png" "UnEnanoMas1.png" ...

And to check the skin to see if the skin that has entered is already saved, so that it does not create another unnecessary png

**Comment by TATCHAN0825** [comment]
https://github.com/TATCHAN0825/joinskinsave/commit/31c1d569dd49f8d088cdc0b5e639d6f476108346
implemented

**Comment by TATCHAN0825** [comment]
https://github.com/TATCHAN0825/joinskinsave/commit/31c1d569dd49f8d088cdc0b5e639d6f476108346
implemented
